services:
    laravel:
        build:
            context: ./FAQ/back_laravel
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
            - "5173:5173"
        tty: true
        stdin_open: true
        volumes:
            - ./FAQ/back_laravel:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:YOUR_APP_KEY
        depends_on:
            - mysql

    react:
        build:
            context: ./exploring-hooks
            dockerfile: Dockerfile
        container_name: react_app
        ports:
            - "3000:3000"
        volumes:
            - ./exploring-hooks:/usr/src/app
        environment:
            - NODE_ENV=development

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
